networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

  R1R2br:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  onos:
    image: onosproject/onos:latest
    container_name: onos
    hostname: onos
    privileged: true
    networks:
      - default
    environment:
      - ONOS_APPS=drivers,fpm,fwd
    ports:
      - "2620:2620"
      - "6653:6653"
      - "8101:8101"
      - "8181:8181"
    tty: true
    stdin_open: true
    command:
      - |
        app activate fwd
        app activate fpm
  # AS65000
  h1:
    image: host
    container_name: h1
    privileged: true
    build:
      context: .
      dockerfile: host.Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    network_mode: "none"
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        ip route del default 
        ip route add default via 172.18.0.2
        sleep infinity

  R1:
    image: frrouting/frr-debian
    container_name: R1
    hostname: R1
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      R1R2br:
        ipv4_address: 172.20.0.2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config/daemons:/etc/frr/daemons
      - ./config/R1/frr.conf:/etc/frr/frr.conf
      - ./config/R1/zebra.conf:/etc/frr/zebra.conf
  # AS65001
  h2:
    image: host
    container_name: h2
    privileged: true
    build:
      context: .
      dockerfile: host.Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    network_mode: "none"
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        ip route del default 
        ip route add default via 172.19.0.2
        sleep infinity

  R2:
    image: frrouting/frr-debian
    container_name: R2
    hostname: R2
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      R1R2br:
        ipv4_address: 172.20.0.3
    volumes:
      - ./config/daemons:/etc/frr/daemons
      - ./config/R2/frr.conf:/etc/frr/frr.conf
